language: node_js
node_js:
  - '10'
cache: yarn
install:
  - 'cd web'
  - 'npm install'
script:
  - 'npm run test'
  - 'CI=false npm run build'

before_deploy:
  - 'cp -R /build ../backend-api/static'
  - 'cd ../backend-api'
  - 'ls'

deploy:
- provider: elasticbeanstalk
  skip_cleanup: true
  provider: elasticbeanstalk
  access_key_id: $ACCESSKEYID
  secret_access_key: $SECRETACCESSKEY
  region: 'eu-central-1'
  app: 'rimac-m2m'
  env: 'm2m-dev'
  bucket_name: 'elasticbeanstalk-eu-central-1-rimac-m2m'
  on:
    branch: develop

