language: node_js
node_js:
  - '10'
cache: npm
install:
  - 'cd backend-api'
  - 'npm install'
script:
  - 'npm run test'
  - 'npm run build'

deploy:
  provider: elasticbeanstalk
  access_key_id: $ACCESSKEYID
  secret_access_key:
    secure: $SECRETACCESSKEY
  region: 'eu-central-1'
  app: 'rimac-m2m'
  env: 'RimacM2m-env'
  bucket_name: 'elasticbeanstalk-eu-central-1-rimac-m2m'
  on:
    branch: develop
